### ISSUE TITLE
Error while running errata_upgrade task

### ISSUE THREAD

**Issue by sthirugn** [SatelliteQE/automation-tools#153]
``` sh
out: ****-config-system: rebooting at Mon Mar 2 14:29:11 EST 2015
out: Warning: run() received nonzero return code -1 while executing 'tail -f /var/log/***sd'!

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 384, in execute
    multiprocessing
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 274, in _execute
    return task.run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/automation_tools/__init__.py", line 1393, in errata_upgrade
    sock.connect((env['host'], 22))
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 111] Connection refused
```

**Comment by elyezer** [comment]
During my development tests I did not get connection refused. Maybe adding a couple more seconds before trying to connect would fix.

@sthirugn one question, this task is working in a reliable way? I mean is errata package working and restarting the system as expected now?

**Comment by rplevka** [comment]
I believe this is no longer an issue and that the code base already change a bit.
If you think otherwise, please reopen.
