### ISSUE TITLE
TypeError right after running satellite5_iso_install task

### ISSUE THREAD

**Issue by lpramuk** [SatelliteQE/automation-tools#174]
[dell-pe2950-01.lab.eng.rdu.redhat.com] out: Installation complete.
[dell-pe2950-01.lab.eng.rdu.redhat.com] out: Visit https://${FQDN} to create the Red Hat Satellite administrator account.
[dell-pe2950-01.lab.eng.rdu.redhat.com] out: 

[dell-pe2950-01.lab.eng.rdu.redhat.com] run: yum -y update
[dell-pe2950-01.lab.eng.rdu.redhat.com] out: Loaded plugins: product-id, rhnplugin, security
[dell-pe2950-01.lab.eng.rdu.redhat.com] out: This system is receiving updates from RHN Classic or RHN Satellite.
[dell-pe2950-01.lab.eng.rdu.redhat.com] out: Setting up Update Process

[dell-pe2950-01.lab.eng.rdu.redhat.com] out: No Packages marked for Update
[dell-pe2950-01.lab.eng.rdu.redhat.com] out: 

Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/35403905/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/home/jenkins/shiningpanda/jobs/35403905/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 384, in execute
    multiprocessing
  File "/home/jenkins/shiningpanda/jobs/35403905/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 274, in _execute
    return task.run(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/35403905/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/satellite5-installer/automation_tools/__init__.py", line 1011, in product_install
    )[host])
TypeError: 'NoneType' object is not iterable

**Comment by lpramuk** [comment]
Solved as PR #175 was merged
