### ISSUE TITLE
Firewall should restrict access to mongod

### ISSUE THREAD

**Issue by kbidarkar** [SatelliteQE/automation-tools#421]
This link should help fix the issue, 
https://access.redhat.com/documentation/en/red-hat-satellite/6.2/paged/installation-guide/chapter-2-preparing-your-environment-for-installation

Section 2.9 

```
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose]  Facter: error while resolving custom fact "mongodb_is_master": 757: unexpected token at '2016-09-23T10:31:54.717-0400 warning: Failed to connect to 127.0.0.1:27017, reason: errno:111 Connection refused
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] 2016-09-23T10:31:54.718-0400 Error: couldn't connect to server 127.0.0.1:27017 (127.0.0.1), connection attempt failed at src/mongo/shell/mongo.js:146'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] backtrace:
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/2.1.0/json/common.rb:155:in `parse'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/2.1.0/json/common.rb:155:in `parse'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /usr/share/katello-installer-base/modules/mongodb/lib/facter/is_master.rb:8:in `block (2 levels) in <top (required)>'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/facts/facter.rb:35:in `call'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/facts/facter.rb:35:in `to_hash'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/facts/facter.rb:35:in `find'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:194:in `find'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/node.rb:117:in `fact_merge'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/node/plain.rb:17:in `find'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/indirector/indirection.rb:194:in `find'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:208:in `main'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/apply.rb:170:in `run_command'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:344:in `block in run'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:540:in `exit_on_fail'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:344:in `run'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:132:in `run'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in `execute'
[upstream-nightly] out: [ERROR 2016-09-23 10:31:54 verbose] /opt/puppetlabs/bin/puppet:5:in `<main>'
```

**Comment by lpramuk** [comment]
I originally though it's a bug only. 
But yes it can be caused by firewall.

**Comment by lpramuk** [comment]
This mongo error is known by devs, workaround is to start mongo before running installer.

Not an issue for our code

**Comment by lpramuk** [comment]
Though its not set I can still connect to localhost:27017 
```
# iptables -L -n
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:22 ctstate NEW
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:443 ctstate NEW
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:80 ctstate NEW
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8140 ctstate NEW
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:9090 ctstate NEW
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:5647 ctstate NEW
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:5646 ctstate NEW
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:22 ctstate NEW
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8443 ctstate NEW
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:2375 ctstate NEW
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:8000 ctstate NEW
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:69 ctstate NEW
ACCEPT     udp  --  0.0.0.0/0            0.0.0.0/0            udp dpt:53 ctstate NEW
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:5671 ctstate NEW
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:5000 ctstate NEW
ACCEPT     tcp  --  0.0.0.0/0            0.0.0.0/0            tcp dpt:16509 ctstate NEW
...
# nc 127.0.0.1 27017
GET /


fdgkjfdugmiy7ne
vrrtyotiuryo
Ncat: Broken pipe.
```

So this is not definitely firewall setup issue.

**Comment by lpramuk** [comment]
Lets use this issue for implementing section ```2.9. Restricting Access to mongod```

(traceback in 1st comment is unrelated)

**Comment by kbidarkar** [comment]
Yeah sure, we need to get Section 2.9 implemented, this also fails for other jobs, but does not `Error` out.

Also, I had just re-run the foreman-installer by logging into the box and it passed, so not sure why does it fail the first time.

**Comment by kbidarkar** [comment]
This is no longer an issue.
