### ISSUE TITLE
LogAnalyzer Error:UnicodeEncodeError: 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by jyejare** [SatelliteQE/automation-tools#481]
The Encoding Decoding Error in printing the log lines:

```
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/main.py", line 756, in main
    *args, **kwargs
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6-upgrader/automation_tools/satellite6/upgrade/__init__.py", line 196, in product_upgrade
    satellite6_client_upgrade('rhel7', clients7)
  File "/home/jenkins/workspace/satellite6-upgrader/automation_tools/satellite6/log.py", line 80, in __exit__
    execute(fetch_appended_log_lines, host=self.host)
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 386, in execute
    multiprocessing
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 276, in _execute
    return task.run(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6-upgrader/automation_tools/satellite6/log.py", line 78, in fetch_appended_log_lines
    analyze(log_file, content)
  File "/home/jenkins/workspace/satellite6-upgrader/automation_tools/satellite6/log.py", line 134, in analyze
    print_lines(enumerate(content_lines, start=1))
  File "/home/jenkins/workspace/satellite6-upgrader/automation_tools/satellite6/log.py", line 119, in print_lines
    _print_wrapper('{}: {}'.format(i, line))
  File "/home/jenkins/workspace/satellite6-upgrader/automation_tools/satellite6/log.py", line 139, in _print_wrapper
    print(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2192' in position 150: ordinal not in range(128)
```

Priority: **High**
Severity: **High**

**Comment by elyezer** [comment]
The simple solution is, prefix all string where `format` is being called with `u` and all this will be gone.
