### ISSUE TITLE
TypeError when upgrading 6.1 > 6.2 with capsule enabled

### ISSUE THREAD

**Issue by pondrejk** [SatelliteQE/automation-tools#595]
For details see upgrade job number 688, the problem seems to be in 
sync_capsule_repos_to_upgrade:

```
Executing task 'sync_capsule_repos_to_upgrade'
Traceback (most recent call last):
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/main.py", line 757, in main
    *args, **kwargs
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 426, in execute
    results['<local-only>'] = task.run(*args, **new_kwargs)
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6-upgrader/upgrade/runner.py", line 59, in setup_products_for_upgrade
    sat_host, os_version, False if product == 'n-1' else True)
  File "/home/jenkins/workspace/satellite6-upgrader/upgrade/capsule.py", line 69, in satellite6_capsule_setup
    execute(sync_capsule_repos_to_upgrade, cap_hosts, host=sat_host)
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 386, in execute
    multiprocessing
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 276, in _execute
    return task.run(*args, **kwargs)
  File "/home/jenkins/shiningpanda/jobs/8764b415/virtualenvs/d41d8cd9/lib/python2.7/site-packages/fabric/tasks.py", line 173, in run
    return self.wrapped(*args, **kwargs)
  File "/home/jenkins/workspace/satellite6-upgrader/upgrade/helpers/tasks.py", line 163, in sync_capsule_repos_to_upgrade
    '{} '.format(cv_name))[1]) for data in cv_version_data]).pop()
TypeError: string indices must be integers, not str
```

**Comment by sghai** [comment]
Closing this issue from here.. and filed at https://github.com/SatelliteQE/satellite6-upgrade/issues/30
